# Generated by Django 4.2.10 on 2024-02-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=7)),
                ('emp_name', models.CharField(max_length=30)),
                ('emp_age', models.IntegerField(default=21)),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_gender', models.CharField(max_length=1)),
                ('emp_salary', models.IntegerField()),
            ],
        ),
    ]
